### ISSUE TITLE
星店长脚本存在bug

### ISSUE THREAD

**Issue by chennfen** [yangtingxiao/QuantumultX#1]
在圈x里执行了一遍，最后显示80多人的任务完成，但实际打开京东星店长页面后只有20多人成功完成基本任务(签到 浏览 关注)，20多人对应图中上半部分
![9157729F-25F8-4C56-9DC8-479F30093682](https://user-images.githubusercontent.com/34900481/97979366-fb9f6b80-1e09-11eb-806c-bba0b3b3483b.jpeg)

**Comment by yangtingxiao** [comment]
@chennfen 日志有没有？日志中有没有李荣浩呢

**Comment by chennfen** [comment]
有的，日志中基本都成功了

**Comment by chennfen** [comment]
我是打开京东看应援记录时发现应援人数不对劲，然后对比了一下发现是只有上半区的人应援成功，而下半区的基本都没有

**Comment by chennfen** [comment]
@yangtingxiao

**Comment by yangtingxiao** [comment]
@chennfen 我这边试了几个号 看着都成功了，你可以注释掉await mcxhd_starmall_taskList(86); 这句话 重新跑一遍看看

**Comment by chennfen** [comment]
@yangtingxiao 好的，我注释完换个号测试一遍

**Comment by chennfen** [comment]
@yangtingxiao 此次基本没有大的问题，注释了那一行代码。部分店铺小部分任务没完成(正常情况）。非正常是59号店铺和69号店铺，一个对应张继科，另一个没找到，属于没有完成
![DCDEB492-6D39-47BF-ABB7-3A5E75F6A3C9](https://user-images.githubusercontent.com/34900481/97983849-df52fd00-1e10-11eb-9e72-c6d20ef1ceb3.jpeg)
![072501A5-F281-491D-B5EC-77C6EDFB33A4](https://user-images.githubusercontent.com/34900481/97983835-d9f5b280-1e10-11eb-8f85-6b19342ff30a.jpeg)
![2D8B0FF5-48F8-4020-B4DE-54FF88A69B89](https://user-images.githubusercontent.com/34900481/97983846-deba6680-1e10-11eb-81b3-55660c8e6ccc.jpeg)

**Comment by chennfen** [comment]
@yangtingxiao 此次没有出现日志里任务完成了，但是实际却无效的bug

**Comment by yangtingxiao** [comment]
@chennfen 恩 再观察下吧。有可能是接口没有返回数据导致的
