### ISSUE TITLE
大佬，能否支持lxk的多账号cookie？

### ISSUE THREAD

**Issue by liuning0307** [yangtingxiao/QuantumultX#15]
用会话切换有点费事，而且最主要的是我的备用机6s跑两个账号的抽奖机竟然要四五个小时😂，真的遭不住啊。

**Comment by yangtingxiao** [comment]
@liuning0307 明天看看吧 今天没时间了

**Comment by yangtingxiao** [comment]
更新下试试吧

**Comment by liuning0307** [comment]
![995C8769-4956-4F90-9F80-AE064FAE4A04](https://user-images.githubusercontent.com/72370295/106435113-69147400-64ad-11eb-8d33-5f3854732757.png)不管NobyDa cookie是否为空，都是这个。

**Comment by yangtingxiao** [comment]
@liuning0307 等会再更新一下

**Comment by liuning0307** [comment]
感谢大佬！一切正常。
