### ISSUE TITLE
白条领券脚本Cookie问题

### ISSUE THREAD

**Issue by usrnb** [yangtingxiao/QuantumultX#16]
一再提示需要获取Cookie，但获取之后还是不行。

**Comment by yangtingxiao** [comment]
@usrnb 用的谁的获取cookie？我这个目前只支持野比的

**Comment by yangtingxiao** [comment]
@usrnb 我的也这样，我没改东西，应该要京东改东西了，等我今天看看吧

**Comment by usrnb** [comment]
是野比的

**Comment by yangtingxiao** [comment]
@usrnb 我看了，活动结束了，京东金融找不到了，先禁用吧

**Comment by usrnb** [comment]
> @usrnb 我的也这样，我没改东西，应该要京东改东西了，等我今天看看吧

辛苦大佬
