### ISSUE TITLE
大佬，新的白条活动能不能加上啊

### ISSUE THREAD

**Issue by ChoiKarl** [yangtingxiao/QuantumultX#18]
https://m.jr.jd.com/member/rightsCenter/#/whiteV2 
每天0点可以抢0.5元，0.6元，0.7元，0.8元4个白条券

**Comment by yangtingxiao** [comment]
@ChoiKarl 明天看一下

**Comment by ChoiKarl** [comment]
@yangtingxiao 大佬，有进展么。。

**Comment by ChoiKarl** [comment]
@yangtingxiao 确实，0点的时候几乎就是秒没。。。
