### ISSUE TITLE
关于推送通知的问题

### ISSUE THREAD

**Issue by LucaLin233** [yangtingxiao/QuantumultX#19]
请教大佬，京东抽奖机和京东排行榜如何发送通知到server酱和TGBot，对于smartreplace看的不是很明白。。
添加
CUSTOM_REPLACE
{key : /let jdNotify.+/,value : "let jdNotify = true"}
至secrets也不推送，恳请解惑

**Comment by yangtingxiao** [comment]
@LucaLin233 通知和smartreplace没关系，自己去看下lxk的通知怎么弄就可以了

**Comment by LucaLin233** [comment]
> @LucaLin233 通知和smartreplace没关系，自己去看下lxk的通知怎么弄就可以了

但我添加了server酱和TGBot的相关yml代码和secret，没有收到通知。。还请大佬指点= =

**Comment by q4w5e6** [comment]
> > @LucaLin233 通知和smartreplace没关系，自己去看下lxk的通知怎么弄就可以了
> 
> 但我添加了server酱和TGBot的相关yml代码和secret，没有收到通知。。还请大佬指点= =

脚本没有调用，你自己加有什么用呢？

**Comment by LucaLin233** [comment]
> > > @LucaLin233 通知和smartreplace没关系，自己去看下lxk的通知怎么弄就可以了
> > 
> > 
> > 但我添加了server酱和TGBot的相关yml代码和secret，没有收到通知。。还请大佬指点= =
> 
> 脚本没有调用，你自己加有什么用呢？

明白了，我去看看
