### ISSUE TITLE
请问能提供金榜创造营的脚本吗

### ISSUE THREAD

**Issue by berkejf** [yangtingxiao/QuantumultX#21]
入口在京东排行榜里面，

https://h5.m.jd.com/babelDiy/Zeus/2H5Ng86mUJLXToEo57qWkJkjFPxw/index.html

谢谢

![Screenshot_2021-05-21-07-15-00-065_com jingdong app mall](https://user-images.githubusercontent.com/882933/119118035-ede7c580-ba7d-11eb-9139-9c40e0b32eef.png)

**Comment by EchoChan314** [comment]
https://raw.githubusercontent.com/qqsdff/script/main/jd/jd_jbczy.js

**Comment by berkejf** [comment]
谢谢。
