### ISSUE TITLE
 ️动物联萌 报错

### ISSUE THREAD

**Issue by Naughty-Monkey** [yangtingxiao/QuantumultX#22]
️动物联萌, 错误!
TypeError: Cannot read property 'nickname' of undefined
    at /jd/scripts/jd_zoo.js:79:38
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jd_zoo.js:981:4791)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by yangtingxiao** [comment]
@Naughty-Monkey 获取用户名交易异常，注释掉79行试试

**Comment by acoolbook** [comment]
> @Naughty-Monkey 获取用户名交易异常，注释掉79行试试 大佬，你这个脚步怎么填助力码助力，我看你的助力已经满了，如何自己小号助力自己呢，我尝试把助力码填入开头那个sharecodelist数组中，但是运行似乎无效

**Comment by yangtingxiao** [comment]
@acoolbook 改658行

**Comment by acoolbook** [comment]
> @Naughty-Monkey 获取用户名交易异常，注释掉79行试试



> @acoolbook 改658行

感谢大佬，请问填多个助力码怎么填

**Comment by yyetss** [comment]
感谢作者。请问多账号填写助力用什么隔开？
