### ISSUE TITLE
放技能bug

### ISSUE THREAD

**Issue by bjl101501** [yangtingxiao/QuantumultX#24]
过了22点还有技能的话，运行脚本会卡循环
`技能释放失败：现在不在活动期间哦~`
哈哈，我也是刚刚运行脚本才发现的

**Comment by yangtingxiao** [comment]
@bjl101501 收到

**Comment by bjl101501** [comment]
> @bjl101501 收到

大佬，放技能还在卡循环，这次是打破铠甲以后
`技能释放失败：队伍任务已经完成，无法释放技能!`

**Comment by yangtingxiao** [comment]
@bjl101501 等会再更新下

**Comment by bjl101501** [comment]
另外提个建议，但是我也没有计算过不知道那种方式收益更高，像我们助力少的，有两个选择，打破铠甲红包更多，但是晚上就面临没有技能可用的局面，又被抢了，不知道能不能加个放技能的开关，纯小白试过注释修改一下结果都是错误😂

**Comment by yangtingxiao** [comment]
@bjl101501 加上了 自己改为false即可

**Comment by bjl101501** [comment]
感谢大佬👍👍👍
