### ISSUE TITLE
618不会自动收金币了

### ISSUE THREAD

**Issue by aidu1001** [yangtingxiao/QuantumultX#25]
data.data.result.produceScore这边一直会出错，取不到数据

**Comment by yangtingxiao** [comment]
@aidu1001 加密问题 等待修复

**Comment by aidu1001** [comment]
我看多了一个post中多了log字段。这个字段数字如果删除，会火爆，保留会正常，然后过半小时或一小时，这个字段数据会无效，会火爆。

**Comment by fanshi1in** [comment]
> @aidu1001 加密问题 等待修复

修改rnd和body解决火爆账户验证加密
let rnd = Math.floor(1e6 + 9e6 * Math.random()).toString()
body={"ss":"{\\"extraData\\":{\\"log\\":\\"-1\\",\\"sceneid\\":\\"QD216hPageh5\\"},\\"secretp\\":\\"${$.secretp}\\",\\"random\\":\\"${rnd}\\"}"}

[加密js供参考](http://storage.360buyimg.com/babel/00926763/2558291/production/dev/index.d7c7085eb6e518060f3e.js?t=20210527170311)

**Comment by fanshi1in** [comment]
> @yangtingxiao 加密问题 等待修复

修改rnd和body可以暂时解决火爆账户验证加密
let rnd = Math.floor(1e6 + 9e6 * Math.random()).toString()
body={"ss":"{\"extraData\":{\"log\":\"-1\",\"sceneid\":\"QD216hPageh5\"},\"secretp\":\"${$.secretp}\",\"random\":\"${rnd}\"}"}

[加密js供参考](http://storage.360buyimg.com/babel/00926763/2558291/production/dev/index.d7c7085eb6e518060f3e.js?t=20210527170311)

**Comment by yangtingxiao** [comment]
@fanshi1in -1你试过 可以吗 这个我研究完了 正在测试

**Comment by fanshi1in** [comment]
> @fanshi1in -1你试过 可以吗 这个我研究完了 正在测试

可以的 在else分支语句中可以查到 log:-1 并且你可以测试一下收金币 ，正常号也可以用

**Comment by yangtingxiao** [comment]
@fanshi1in 好 那我先整成-1

**Comment by aidu1001** [comment]
确实可以。

**Comment by yangtingxiao** [comment]
@fanshi1in 测了一下 更新上去了 这样省事了 等-1火爆的时候我再改成研究出来的算法😂

**Comment by GitCourser** [comment]
大佬, 用击两天又开始火爆了

**Comment by yangtingxiao** [comment]
@GitCourser 恩 已经知道了 目前还是有部分帐号可用，等更新

**Comment by aidu1001** [comment]
大佬。晚上全部都火爆了
