### ISSUE TITLE
jd_zoo出现错误

### ISSUE THREAD

**Issue by hdstar2009** [yangtingxiao/QuantumultX#32]
已使用最新jd_zoo.js版本
每个账号都有这个错误
Jun 09 18:14:23 ❗️动物联萌, 错误!
Jun 09 18:14:23 TypeError: Cannot read property 'split' of undefined
Jun 09 18:14:23     at /scripts/jd_zoo.js:753:168
Jun 09 18:14:23     at runMicrotasks (<anonymous>)
Jun 09 18:14:23     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Jun 09 18:14:23     at async /scripts/jd_zoo.js:753:13

**Comment by carlolin** [comment]
我能请教那段加密得js是怎么的来得吗

**Comment by yangtingxiao** [comment]
@hdstar2009 你这个用的是我的吗？

**Comment by hdstar2009** [comment]
> @hdstar2009 你这个用的是我的吗？

是你的，我从这下载后复制到docker里面运行，我刚刚还看了下js内容，开头更新时间 更新时间：2021-06-09 13:52
确认。

**Comment by hdstar2009** [comment]
> @hdstar2009 你这个用的是我的吗？

现在手工又执行一次，每个账号都是由如下错误（账号都做完任务的）

Jun 09 20:28:35 ❗️动物联萌, 错误!
Jun 09 20:28:35 TypeError: Cannot read property 'nickname' of undefined
Jun 09 20:28:35     at /scripts/jd_zoo.js:72:38
Jun 09 20:28:35     at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/scripts/jd_zoo.js:853:4791)
Jun 09 20:28:35     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Jun 09 20:28:35
Jun 09 20:28:35
Jun 09 20:28:35 京东账号： 任务开始
Jun 09 20:28:35 签到结果：已签到
Jun 09 20:28:35 您的队伍助力码：sSKNX-MpqKOJsNv4--OzQaeMAlZZMzx8iqK_K4uvrKtVXx214Cj_Ir1w
Jun 09 20:28:35
Jun 09 20:28:35 收取金币：7884
Jun 09 20:28:39
Jun 09 20:28:39 ❗️动物联萌, 错误!
Jun 09 20:28:39 TypeError: Cannot read property 'split' of undefined
Jun 09 20:28:39     at /scripts/jd_zoo.js:753:168
Jun 09 20:28:39     at processTicksAndRejections (internal/process/task_queues.js:95:5)
Jun 09 20:28:39     at async /scripts/jd_zoo.js:753:13

**Comment by yangtingxiao** [comment]
@hdstar2009 应该是兼容性问题

**Comment by hdstar2009** [comment]
> @hdstar2009 应该是兼容性问题

动物这个用脚本从第二天开始，之前没遇到过这样的问题，就今天的脚本。

**Comment by yangtingxiao** [comment]
@hdstar2009 明天我改进一下吧

**Comment by yangtingxiao** [comment]
更新试一下吧

**Comment by hdstar2009** [comment]
> 更新试一下吧

没出现错误了。不过，你这个脚本不带多账号之间自动助力的功能？之前都是用lxk的脚本，昨天才换你的脚本，不火爆能修复，只是不能自动助力这个麻烦啊。能加上吗？

**Comment by yangtingxiao** [comment]
> > 更新试一下吧
> 
> 没出现错误了。不过，你这个脚本不带多账号之间自动助力的功能？之前都是用lxk的脚本，昨天才换你的脚本，不火爆能修复，只是不能自动助力这个麻烦啊。能加上吗？

工作比较忙，暂时没时间处理，你可以把我倒数第二行 替换lxk的倒数第二行就可以了 ，那样就不会火爆了。

**Comment by hdstar2009** [comment]
> > > 更新试一下吧
> > 
> > 
> > 没出现错误了。不过，你这个脚本不带多账号之间自动助力的功能？之前都是用lxk的脚本，昨天才换你的脚本，不火爆能修复，只是不能自动助力这个麻烦啊。能加上吗？
> 
> 工作比较忙，暂时没时间处理，你可以把我倒数第二行 替换lxk的倒数第二行就可以了 ，那样就不会火爆了。

倒数第二行是var _0xodI=开头那行？替换过去不行，一开始就报 secretp is not defined，最后错误如下：
618动物联萌, 失败! 原因: ReferenceError: secretp is not defined!

**Comment by yangtingxiao** [comment]
@hdstar2009 再把那句话中的'secretp':secretp改为 'secretp':$.secretp 因为两个脚本的这个变量名不一样
