### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by carlolin** [yangtingxiao/QuantumultX#33]
能跟你请教一下 jd_zoo.js 最后的那两行js 怎么来的吗

**Comment by yangtingxiao** [comment]
@carlolin 最后那个是chavyleung大佬写的框架 倒数第二行我自己写的加密之后的

**Comment by carlolin** [comment]
你是反编译狗东app 然后自己写出来的吗。能不能分享一下加密前的js   13726704189@163.com

**Comment by carlolin** [comment]
或者分享一下你的思路， 可以吗
