### ISSUE TITLE
动物联萌好像火爆了

### ISSUE THREAD

**Issue by charleyyy** [yangtingxiao/QuantumultX#36]
两个账号，一个正常一个火爆

**Comment by yangtingxiao** [comment]
加密算法升级，研究中

**Comment by H-hao** [comment]
> 加密算法升级，研究中

大佬，可以分享一下解密的思路吗？

**Comment by qsls9** [comment]
手动玩是正常的，而且火爆也是部分账号，是不是跟风控等级有关呢

**Comment by qsls9** [comment]
> 加密算法升级，研究中
手动玩是正常的，而且火爆也是部分账号，是不是跟风控等级有关呢
