### ISSUE TITLE
京东排行榜

### ISSUE THREAD

**Issue by Twinzo1** [yangtingxiao/QuantumultX#4]
京东排行榜检测的是昨天是否签到，因此只能隔一天签一次，望大佬修复一下

**Comment by yangtingxiao** [comment]
@Twinzo1 你是在action运行的？

**Comment by Twinzo1** [comment]
是的

**Comment by Twinzo1** [comment]
我明白了，我改下运行时间看看

**Comment by yangtingxiao** [comment]
@Twinzo1 因为北京时间问题，utc时间建议你设置到16点以后运行，也就是北京时间8点以后，这样就不会有问题

**Comment by yangtingxiao** [comment]
@Twinzo1 对的，因为这个晚了也没事，懒得改脚本判断了

**Comment by Twinzo1** [comment]
明白了，我先试试看

**Comment by Twinzo1** [comment]
大佬，刚刚手动运行后，日志显示的也是判断昨天的已签到![image](https://user-images.githubusercontent.com/44726207/99320022-9e91c400-28a5-11eb-8afb-d47e3be8ca84.png)

**Comment by yangtingxiao** [comment]
@Twinzo1 北京时间8点以后运行，现在这个 utc还不到17号

**Comment by Twinzo1** [comment]
😂明白，我八点后再试一次

**Comment by Twinzo1** [comment]
可以了，谢谢大佬😊

**Comment by yangtingxiao** [comment]
脚本已经改了，凌晨运行也没问题了

**Comment by Twinzo1** [comment]
> 脚本已经改了，凌晨运行也没问题了
😊👌
