### ISSUE TITLE
动物联萌还是火爆

### ISSUE THREAD

**Issue by danwangshi** [yangtingxiao/QuantumultX#44]

**Comment by yangtingxiao** [comment]
@danwangshi 明天修

**Comment by Agameadream** [comment]
> @danwangshi明天修

倒数第二行的加密部分，替换到lxk脚本中运行报错 f+=_0x3e8f57 这里赋值不上

**Comment by Agameadream** [comment]
> > @danwangshi明天修
> 
> 倒第二行的部分，替换到lxk脚本中运行f+=_0x3e8f57这里弹出不上

看了下发现我少加了最上面的joytoken，
