### ISSUE TITLE
白条脚本更新后如果本机时间对不上，就跑错日期领取了，希望修复

### ISSUE THREAD

**Issue by Jones0207** [yangtingxiao/QuantumultX#6]
白条脚本更新后如果本机时间对不上，就跑错日期领取了，希望修复

**Comment by yangtingxiao** [comment]
在什么上面运行的啊？

**Comment by Jones0207** [comment]
10月29号的版本运行可以读取网络时间，现在最新版本如果我本地时间是周二则运行领取周二的优惠券。我是放腾讯云运行，读取不到时间就直接不领取周一到周日的白条

**Comment by yangtingxiao** [comment]
因为加入了9点的判断，如果时区不对的话可能会有问题。要确保自己的时间差的不是太多，脚本里面我也修改一下

**Comment by yangtingxiao** [comment]
应该没啥问题了，更新下明天看一下

**Comment by Jones0207** [comment]
更新了测试了应该没问题了，多谢大佬
