### ISSUE TITLE
天天挖矿获取不到cookie了

### ISSUE THREAD

**Issue by r0ckrise** [yangtingxiao/QuantumultX#9]
之前使用正常，点签到就能获取了，现在点签到也获取不到了。

**Comment by yangtingxiao** [comment]
@r0ckrise 可能链接改了，之前获取的还能用，等我白天看一下吧

**Comment by yangtingxiao** [comment]
@r0ckrise 更新了，明天签到的时候重新获取下试试吧

**Comment by r0ckrise** [comment]
> @r0ckrise 更新了，明天签到的时候重新获取下试试吧

可以了，感谢大佬。

**Comment by r0ckrise** [comment]
获取后没去管，今天看日志发现以下错误了。

iOS 13.5 NE v1.0.18-build475

Logs:


🔔天天挖矿, 开始!
{"timestamp":1610753189158,"status":404,"error":"Not Found","message":"No message available","path":"/api/mining/v2/sign/showSignInfo"}

❗️天天挖矿, 错误!
TypeError: undefined is not an object (evaluating 'data.data.hasSign')

🔔天天挖矿, 结束! 🕛 0.797 秒

**Comment by yangtingxiao** [comment]
@r0ckrise 知道了，链接是改了，我再改一下吧

**Comment by r0ckrise** [comment]
> @r0ckrise 知道了，链接是改了，我再改一下吧

已更新，感谢大佬
